In [26]:
import pandas as pd
import seaborn as sns

In [27]:
House=pd.read_csv("7.2_HousePricePrediction.csv")
House.head(15)

,Id,MSSubClass,MSZoning,LotArea,LotConfig,BldgType,OverallCond,YearBuilt,YearRemodAdd,Exterior1st,BsmtFinSF2,TotalBsmtSF,SalePrice
0,0,60,RL,8450,Inside,1Fam,5,2003,2003,VinylSd,0.0,856.0,208500.0
1,1,20,RL,9600,FR2,1Fam,8,1976,1976,MetalSd,0.0,1262.0,181500.0
2,2,60,RL,11250,Inside,1Fam,5,2001,2002,VinylSd,0.0,920.0,223500.0
3,3,70,RL,9550,Corner,1Fam,5,1915,1970,Wd Sdng,0.0,756.0,140000.0
4,4,60,RL,14260,FR2,1Fam,5,2000,2000,VinylSd,0.0,1145.0,250000.0
5,5,50,RL,14115,Inside,1Fam,5,1993,1995,VinylSd,0.0,796.0,143000.0
6,6,20,RL,10084,Inside,1Fam,5,2004,2005,VinylSd,0.0,1686.0,307000.0
7,7,60,RL,10382,Corner,1Fam,6,1973,1973,HdBoard,32.0,1107.0,200000.0
8,8,50,RM,6120,Inside,1Fam,5,1931,1950,BrkFace,0.0,952.0,129900.0
9,9,190,RL,7420,Corner,2fmCon,6,1939,1950,MetalSd,0.0,991.0,118000.0
10,10,20,RL,11200,Inside,1Fam,5,1965,1965,HdBoard,0.0,1040.0,129500.0
11,11,60,RL,11924,Inside,1Fam,5,2005,2006,WdShing,0.0,1175.0,345000.0
12,12,20,RL,12968,Inside,1Fam,6,1962,1962,HdBoard,0.0,912.0,144000.0
13,13,20,RL,10652,Inside,1Fam,5,2006,2007,VinylSd,0.0,1494.0,279500.0
14,14,20,RL,10920,Corner,1Fam,5,1960,1960,MetalSd,0.0,1253.0,157000.0

In [28]:
House.isnull()

,Id,MSSubClass,MSZoning,LotArea,LotConfig,BldgType,OverallCond,YearBuilt,YearRemodAdd,Exterior1st,BsmtFinSF2,TotalBsmtSF,SalePrice
0,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2914,False,False,False,False,False,False,False,False,False,False,False,False,True
2915,False,False,False,False,False,False,False,False,False,False,False,False,True
2916,False,False,False,False,False,False,False,False,False,False,False,False,True
2917,False,False,False,False,False,False,False,False,False,False,False,False,True
2918,False,False,False,False,False,False,False,False,False,False,False,False,True

In [41]:
House=House.fillna(0)

In [36]:
House["MSZoning"]=House["MSZoning"].map({"RL":1,"RM":0})

x=House.drop(columns=["LotConfig","BldgType","Exterior1st","SalePrice"],axis=1)
y=House["SalePrice"]

In [48]:
x=x.fillna(0)
y=y.fillna(0)

In [49]:
from sklearn.model_selection import train_test_split

In [50]:
x_train,x_test,y_train,y_test=train_test_split(
    x,y,test_size=0.2,random_state=50)

In [51]:
from sklearn.linear_model import LinearRegression

In [52]:
model=LinearRegression()
model.fit(x_train,y_train)

LinearRegression()

In [53]:
y_pre=model.predict(x_test)

In [54]:
y_pre

array([283255.66406707,  36204.97350706, 213067.09693936,  30607.44569689,
        56587.61365214, -20996.29384906, 103209.55873692, 194233.80235214,
       155256.58063555, 108441.5316393 ,  61500.95996666, 162332.82142714,
       143703.71693632, 194446.7378872 , 203542.89444537,  60578.51897797,
        51947.81141027, 166231.15844537, 207271.73555595, 248947.94245803,
        36144.21911777, 107856.4214018 , 135661.07697862, 216136.1839929 ,
       -45953.0059269 , 169125.40011935, -39109.76815788,  -8447.95640118,
        10247.06627985, -15099.40180017, 171156.1902959 , 185717.20768009,
       150525.16816454,  64328.6960698 , 167376.11884036, -98156.29073981,
         -812.03124972, 213488.38873966,  -2880.13069165,   5312.3659587 ,
       162991.73725361, 136446.47842044,  53864.04827755, -17757.93810195,
        31454.09944235,  83169.57416204, 147665.48214691, 229847.94917635,
       -11314.29748596, 210268.68250321, -33436.12206914, -21919.85079814,
        40373.43217988,  10965.6829847 ,  36246.86972188, 148016.01918442,
        45130.96591734,  70817.91069086, 137278.36158666, -28661.0873203 ,
       157417.02841748, 186019.10013402, -22121.05466648, 142874.18968208,
       136981.41084015, -27431.97262959,  69374.96575701, 155810.46773327,
       247831.4206248 , 218130.40186302, 198937.12182042, 133544.43896692,
        96663.72601411, 123824.92192292,  -2889.87312373, 171525.99861424,
        50981.0028412 , 177638.48690169, -43618.15081938,  -6988.52647779,
       246571.60800487, -43112.64788585, 109720.04397998, 140180.23320373,
       126596.52736841,  44048.90717311,  12506.98792974, 118275.33233493,
        17498.28665195,  94995.20945882,  94576.45400412,  74797.27484103,
        17387.4645208 ,   6064.89337766, 182785.7096982 , 107921.72549465,
       105834.38462919,   4458.26544213,  18149.40167579, 231782.79924346,
       167487.21444143, 239038.74779717,  33029.53440105, -18141.51480077,
        20246.56633994,  31014.24819419, -15629.38032203, -29728.17984765,
       -23079.74062742, -67993.02441472, -18879.70685626, 164143.26643322,
        73886.61422586,   4212.60884709, 184082.12068985, -26934.32578127,
       125437.98096075, 197223.2584181 ,  37183.55022835, 143756.63762157,
       112387.62381205, 169545.0465997 , -50275.00941501, 221808.75173012,
        24106.34652312, -14805.58307931, -39506.40073056, 101290.59612747,
       193228.32896326,   1097.62528136,  63523.39908191,  14177.49847448,
       188569.19982933,  83112.30378279,   7042.23974624, 112428.64357092,
       247751.95384774, -21731.54661073,  50206.1563171 ,  52788.64723328,
       -36852.64332425,  10212.28099997, 153268.16445756, 230030.94396779,
       182014.31468225,  35395.90587692, 129499.84229361, 122657.67890611,
       -20626.32423475,  33218.68672432, -13269.38470328,  68188.72777983,
       170090.01999213, 187715.31732853,   8422.21891764,   1767.7112446 ,
       -17097.85840775, 149894.04201455, 110035.32131476, 166071.41754135,
       190426.19490046, 259335.77042751,  55650.77364114, 206568.09028691,
        43224.87008956, -14340.90212884,  66336.06404135, 203989.7917502 ,
        60843.32136898,  60977.06121047, -32871.42950198, 192565.14464474,
        88114.11847502, 208279.3611401 , -76710.24420414, 188272.32729784,
        81546.15635645,  86818.72035951, 187294.77089739,   8718.7960817 ,
       170526.71172968,  72394.70751673, 193515.18074439,  37176.97906582,
        49717.29463647, 166024.33405559, 227642.4310296 , 198074.71271218,
       119608.02274179, -17483.50571851, 104773.19780027, -24138.0798015 ,
        51785.86359149,  84638.55768023, 163847.32330777, 197096.39483722,
        51017.96113605, 152912.5605138 ,  13976.84098685, 166190.8966109 ,
        10167.12010658, -16973.47603591, 164167.6403456 ,  -2468.97928594,
        89901.84013852, 221070.48249592,  46192.00135665, 101517.9451092 ,
        17400.74425421, 169595.74795009,  79554.07130929,  -3905.64122394,
       145864.97122629,  49668.51291037,  78179.4461212 , -54692.17060531,
       -74145.50424685, 161060.89917548, -17811.85470326, 137824.56208015,
       185861.1470045 , 158978.91482978,  59536.33292605,  23329.49619264,
       180420.26136283,  46755.95482147, -74941.39813966,  -7568.25800866,
        86470.90599813, 215957.88119355,  69489.62855636, 164638.92322007,
       -53854.43251698,  55125.95961226, -20202.86125681, -21024.90274841,
       -17925.49007139,  65933.41825987,  74703.55660272, 104835.11952689,
         1439.17090643,  64191.02813842, 169826.65225873, 172533.05536851,
         1411.10398145,  94855.81924793,  23767.06996649,  84197.069081  ,
       -19199.3682491 ,  73659.37391159,  57628.01151031, -10652.71246809,
       182785.0218667 , -71096.60626449, -33292.21796863, 114850.00960291,
       152320.48022442, 177975.01092226, 176741.17352018,  96734.92401928,
        31485.18323625, 119637.12329364,  32966.49059607, 164941.5071741 ,
        67791.45971285,  25439.42383339, -17416.96550028, -59015.23299513,
       188739.01443442, 203548.84541002, 128079.53360567, 194276.86460359,
        67553.48303193, 159233.40754216,  22677.82006553, 256714.6196938 ,
       -16472.91935171, 116882.20479582, 116187.54090564,  14946.38766767,
       128990.85067992, -18190.17463812, 127311.20384538,  85976.89644502,
        53030.48684764, 156427.9780817 , 131502.48955132, 102016.72914998,
        93250.85541011, 215265.58342567, 223359.62664497,  14983.7743905 ,
       140995.88191265, 218432.83859412, -50250.10672045, 165799.4503739 ,
       136361.47949929, 143766.08778807,  16266.50432894, 257021.76367742,
       152089.22587427, 199917.20681705,  14215.53189042,  83209.92073506,
       201991.25990808, 172708.80355685, -66551.9062738 ,  98300.32232325,
        61305.26401305, 176816.8725539 , 148597.55439997,  64316.66746689,
       212324.14255307, 136602.94559754, 246272.90899484,  26741.9342209 ,
        95137.86140924, 265214.61330382, 217405.27326363, 174920.60706786,
        26783.30267058, 159813.76642079,  32193.82500041,  66738.63655781,
       -11039.06868826,  87295.53444537,  99598.33257   ,  56056.15501212,
        53119.97454623,  54686.14580794, -11113.70471922, 185981.45088634,
       245846.50016462, 205451.85896202,  72172.01866652, -25002.07934019,
        67690.09919388, 140066.95359188, 226110.30211379,  33209.79183928,
       152773.81175603, 117939.44162718, -61125.91127939, 152225.8154177 ,
       -34053.47021943, 144854.1570552 , -46688.23975175,   -963.27722333,
        34927.74843802,  68594.92393857, 210418.94809122,  32186.19416117,
       102079.57410313, -67068.83116891, 195175.17171326,  77999.0117794 ,
       -19732.05267915, 165201.87529952,  80661.67355715, 155296.9551904 ,
       101485.26219113, 247677.51666882, 202277.88361275,  38580.43155743,
       249350.92542144,  65074.39963194,  62072.5953568 , 165648.4509065 ,
       215094.86216355,  96099.5011788 , 149132.80550172, 184943.34816429,
        82582.03637949, 188409.48962739, -12935.36713455, 177632.30262396,
        21887.46516008, -16807.00407974, 105977.44703968, 124953.44648807,
        29239.53704023,  79586.57757761,  55159.70424438, 142060.6966104 ,
       -25103.61426269,  68758.68141242, 183199.53570703, 193027.82358954,
       265741.77540501, 171166.01466038, 237499.18947257, 175089.11828751,
        46858.23333848, 124076.0914659 , -49469.02698038,   4183.37161918,
        34441.69565077,  18427.23988991,   3781.70585874,  60467.72167569,
       221685.2358231 , 270171.6591419 , 122420.15140825, -39263.68748261,
       131581.02075594,   3664.19000638, 187310.19092134,  92496.14561891,
        26725.81466702,   8272.87453546,  84185.74379308,  89968.8110208 ,
       -65606.37896937,  94828.58960801,  96976.61415544, 224588.535907  ,
       207855.07948324,  59523.94067386,  31647.01545985, -32614.37168558,
       219671.92612021, 133526.68558559,  89985.28926592, 212290.14123474,
       138725.5719938 , 129433.44501259, 129370.01111181, -18286.18455955,
       138476.95892492,  43263.05616231,   5553.59799907, 144856.15575309,
       -48698.82575435, 140383.80876604, -21645.43815668,  57867.85615822,
        41470.7362797 , -17988.90663714, 133561.26479163, 145773.10875859,
        79192.64872977, -36541.68567296,  18330.12858827,  26515.33901203,
        42620.17082593, 134279.98778724, 590615.68108088, 100951.61582005,
       234584.13059552,   4839.03016608, 193847.31225001, 219984.70677518,
        57800.10241291, -20233.0064674 , 181004.21110841,  29291.37543178,
       142459.25196898, 146037.25047665, 162542.59596404, 110308.63222009,
       124959.71823497, 234546.36067945, -48716.21744023,  66316.48060759,
         4190.54965912, 196487.90090509, 211101.21796448, 196748.4667448 ,
        95754.6897361 ,  44544.53266734,  97511.80759121,  28596.47174559,
       109765.62132494,  23912.88933835,  56664.4390704 , 213406.19048748,
       163179.74451826, 168154.53032711,  65631.74820821,  16005.03446935,
       217140.58825607, 196447.82512158, -44450.56924201, -27036.06997411,
       228358.23146951,  98322.59281113, 176110.94523438, 173951.45885369,
       -35750.96708488, -14614.5614216 ,  52497.06804715, 184269.69480623,
       418601.34818228,  49576.77521455, 132211.93391954, -83704.45937877,
        53818.10600569,  76205.81240137,  41236.3312079 , 201690.978668  ,
       114641.56379529,  24755.34568983,  83182.76754302,   6865.1641201 ,
       112534.23269344,  42057.0169973 ,  10463.54959094, 151040.98721374,
       128088.39930703,  30249.41428368,  34379.99346162, -95648.09447583,
        32833.67221804,  85577.39090499, 171068.38163398, 494880.55746387,
       108509.84327319,  38625.5625264 , 198027.97121407,  92686.56367169,
       108372.62753217, 166645.3647817 , -23788.47618907,  -8332.75295555,
       123915.65983711, 219841.33039887, 121922.23156565,  52219.73970166,
        31105.24046012, 101083.65603103,  -3918.86747263, -16029.83930361,
         6633.83109798, -40341.02565919, -86863.57297767, 149555.41155031,
       169017.25143213, -19105.99620698,  36073.91069177, 136877.45719022,
        85729.06484503,  91436.10763798, 141630.71954908,  14642.89632768,
       194621.53363963, 114319.34597613,  -7272.12156057, -39378.28708252,
       225601.78682964, -14860.64923597, 151225.6980088 ,  -9290.92979388,
        93260.59299865, -26741.1870502 ,  57106.84612096, 221010.79027791,
        39323.40402539, 194378.02065147, 106111.92457146,  62834.09070661,
       194945.43989563, 116960.03444342, 183744.05319707, 118066.26825805,
       112238.9402243 ,  79990.08404295, 121124.51203877, 127775.31986329,
        41189.4009383 , 166624.03754919, 150498.47992273,  78526.12861115,
        69091.46632603,  -8000.7380184 , 154810.94015722, 147388.2596497 ,
        73370.43509144, 157450.12070775, -43299.64070359, 216676.15000327,
       128717.49489507, 159460.53498115, 237609.63899231,  79534.17841308])

In [57]:
y_test

178     501837.0
1856         0.0
12      144000.0
2028         0.0
2048         0.0
          ...
2549         0.0
1066    178000.0
762     215200.0
1       181500.0
1420    179900.0
Name: SalePrice, Length: 584, dtype: float64

In [56]:
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error
from sklearn.metrics import mean_absolute_percentage_error
import numpy as np

y_pred = model.predict(x_test)

print("R2 Score:", r2_score(y_test, y_pre))
print("MAE:", mean_absolute_error(y_test, y_pre))
print("RMSE:", np.sqrt(mean_squared_error(y_test, y_pre)))
print(mean_absolute_percentage_error(y_test, y_pre))

R2 Score: 0.5971646854663226
MAE: 51804.866003923256
RMSE: 68411.6835648634
1.0294773093495372e+20